const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
const { requireAuth } = require("@clerk/express");
const { protect } = require('../middleware/authMiddleware');
const { ensureAdmin, ensureSignedIn } = require('../middleware/auth');
const { ClerkExpressRequireAuth } = require('@clerk/clerk-sdk-node');
router.post('/register', authController.register);
router.post('/login', authController.login);
router.get('/profile',requireAuth(), authController.getProfile);
router.post('/sync' , requireAuth() , authController.syncClerkUser);
router.get('/users', ClerkExpressRequireAuth() ,ensureAdmin,  authController.getAllUsers);
module.exports = router;
